In [7]:
from google.colab import drive

drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [21]:
import pandas as pd
#!ls '/content/drive/'
#!ls "/gdrive/My Drive/Colab Notebooks/movie_data.csv"
df = pd.read_csv('https://drive.google.com/file/d/17pSHp8mb_RT4c-W7bZB1NoNL18S4t36-/view?usp=sharing', encoding='utf-8')
df.head(3)

<!DOCTYPE html><html><head><meta name="google" content="notranslate"><meta http-equiv="X-UA-Compatible" content="IE=edge;"><style>@font-face{font-family:'Roboto';font-style:italic;font-weight:400;src:local('Roboto Italic')  ... };this.gbar_=this.gbar_||{};(function(_){var window=this;
0                                               try{                                                                                                                                                                              ...                                                NaN       
1                                             var aa                                                                                                                                                                              ...                                                NaN       
2  if("function"==typeof Object.setPrototypeOf)da...                                                                                                                                                                              ...                                                NaN       

[3 rows x 410 columns]

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer(stop_words='english',
                        max_df=.1,
                        max_features=5000)
X = count.fit_transform(df['review'].values) #shape: (50000,5000)

KeyError: ignored

In [0]:
#실행 엄청 오래 걸림!
from sklearn.decomposition import LatentDirichletAllocation

lda = LatentDirichletAllocation(n_components=10,
                                random_state=123,
                                learning_method='batch')
X_topics = lda.fit_transform(X)

In [0]:
n_top_words = 10
feature_names = count.get_feature_names()

for topic_idx, topic in enumerate(lda.components_):
    print("토픽 %d:" % (topic_idx + 1))
    print(" ".join([feature_names[i]
                    for i in topic.argsort()\
                        [:-n_top_words - 1:-1]]))

토픽 1:
worst minutes awful script stupid terrible money waste budget ll
토픽 2:
family mother father children girl loved kids watched friends feel
토픽 3:
american war dvd music tv history german black early america
토픽 4:
human audience cinema art sense feel viewer game different camera
토픽 5:
police guy car dead murder wife goes town killed crime
토픽 6:
horror house sex girl woman blood gore creepy scary night
토픽 7:
role performance comedy actor performances plays played play john excellent
토픽 8:
series episode war episodes tv season action star king western
토픽 9:
book version original read novel disney effects fi sci animation
토픽 10:
action fight guy guys cool fun minutes music nice fighting


In [0]:
lda.components_[4, :].argsort()[:-6:-1]

array([3339, 2032,  681, 1175, 2972])

In [0]:
for i in lda.components_[0, :].argsort()[:-6:-1]:
    print(feature_names[i])

worst
minutes
awful
script
stupid


In [0]:
comedy = X_topics[:, 6].argsort()[::-1] #어떤 topic에 속할 확률이 가장 큰 5개의 index가 반환된다.

for iter_idx, movie_idx in enumerate(comedy[:3]):
    print('\n코미디 영화 #%d:' % (iter_idx + 1))
    print(df['review'][movie_idx][:1000], '...')
    print(movie_idx)


코미디 영화 #1:
"Kramer vs. Kramer" is a terrific drama about an unhappy woman who walks out on her husband and young son. The husband now has to take up the responsibilities of taking care of the boy. As he does, they get to know each other better. But then, the mother and wife returns, and she wants custody of the boy. "Kramer vs. Kramer" has lots of drama with some wonderful bits of comedy thrown in for good measure. Dustin Hoffman won his first Best Actor Oscar for his brilliant performance here. Most people say his performance in "Rainman", which won him his second Oscar, is his best. He was great in that film, but I disagree that its his best. In my opinion, the best performance of Hoffman's career is in this movie. Scene after scene shows us why Hoffman is one of the best American actors working today. He's also funny at times. Also giving a terrific performance is Meryl Streep, who wasn't as well known when she made this film like she is today. Streep, like Hoffman, also won her fi

In [0]:
import numpy as np
np.argmax(X_topics, axis=1)

array([4, 0, 1, ..., 0, 1, 1])

In [0]:
comedy = X_topics[:, 6].argsort()[::-1]
comedy

array([21384, 48528, 31320, ..., 48404, 15111, 25114])

In [0]:
X_topics #각각의 샘플이 어떤 토픽에 속할 확률, shape: (n_samples, n_topics)

array([[0.0011114 , 0.19959939, 0.00111146, ..., 0.00111146, 0.00111178,
        0.00111127],
       [0.9857103 , 0.00158776, 0.00158769, ..., 0.00158763, 0.0015877 ,
        0.00158774],
       [0.38619934, 0.43091153, 0.106478  , ..., 0.00119069, 0.00119094,
        0.00119079],
       ...,
       [0.44586093, 0.0027788 , 0.00277831, ..., 0.00277824, 0.10483994,
        0.09596916],
       [0.00384681, 0.53244645, 0.00384701, ..., 0.00384698, 0.00384675,
        0.00384695],
       [0.00833551, 0.48130427, 0.00833415, ..., 0.00833491, 0.00833449,
        0.45201744]])

In [0]:
X_topics[:, 6].argsort()[::-1] #어떤 topic에 속할 확률이 가장 큰 5개의 index가 반환된다.

array([21384, 48528, 31320, ..., 48404, 15111, 25114])

In [0]:
review_1='''The movie "Avengers: The End Game" (Avengers 4) was released for the first time in the world on Monday (North America 26th). It is a series that has been together for seven years since 'Avengers 1' was released in 2012. It would be safe to say that "Superhero" and "The Avengers" have been condensed into one epic narrative, which has been breathing with fans for a month and a dozen years. It is the sequel to 'Avengers: Infinity War' (Avengers)' that was released in April of last year and the 22nd Marvel film after 'Captain Marvel' (2019).
With half of the universe's life dead by the villain Thanos (Josh Brolin), the Avengers team, joined by the new members, is trying to revive the dead. 
"Avengers, now really good-bye.` 

For fans and actors who have been running for seven years, Marvel seems to be speaking. The movie allowed the long-time hero and the jubilant audience to have enough time to prepare for the farewell. It showcases the memories of more than 20 Marvel Heroes over a decade. For fans who truly care about the Avengers, 180 minutes of running time seems short, let alone boring. 

The Heroes' battle is not easy again this time. "Infinity War," which was released last year, ended with a shocking ending in which villain Thanos mercilessly blew up half of the world's population. The audience had to leave the theater in a bitter mood as Marvel showed the difficult ending of the villain's victory. However this year's 'end game' is different. 

The Avengers, including Iron Man (Robert Downey Jr), Captain America (Chris Evans), Black Widow (Skalit Johansson) and Thor (Chris Hemsworth), eventually find a way to save the world without giving up. 

The answer is time travel that got a clue in quantum mechanics. Actors who have moved to different time and space face themselves in the past. Meet people who can no longer meet in reality, and grow up one step further, looking back on their irrevocable lives. As it has been, the audience can greet the end without letting go of the string of hope to see them fighting for everything they have done. 

The highlight of the movie is also the last battle scene. I can feel the thrill of watching dozens of heroes shouting "Avengers, Assembly!" as if everyone were gathering for the day. It presents catharsis by showing Marvel's message that "individuals join forces to fight against the evil." 

It is also a great pleasure to see the welcome faces that have appeared so far. It is also sad to leave out the "marble-style" humor codes that make audiences burst whenever they can forget, including the newly released "Antman" (Paul Rudd). 

[Ko Bo-hyun, Reporter] 


This may be a quadruple. It is like putting a damper on an audience that has yet to see it. So let's try to control ourselves as much as we can and sum up a word of regret. This is also the foot of a small group of fans who hope that this is not a big part of the series. 

What kind of aesthetic achievement do you expect from Avengers 4? Seven years from Avengers 1 to an individual hero, Marvel Heroes, which have been together for a dozen years, were usually a product of some excess. The epic didn't deviate from its predicted path, and computer graphics and action poured in like a show. 

The ostentatious image was flamboyant, but only so. In other words, he was quickly forgotten after seeing it. This is not the case if there is a movie in which certain shots are remembered for a long time. There was no sudden stop between the galloping epic, the cinematic fascination with the image of the paragraph. So is Avengers 4. 

It is absurd to expect aesthetic moments in popular blockbusters. But we remember commercial films that, despite those limitations, have carved my own authoring seal on the screen. Occasionally, I have entered my own signature directly, sometimes secretly, but also with entertainment. But the Russo-brother doesn't reach that level. 

Perhaps their brilliance is that they have strategically offset the fatigue caused by the excesses of spectacles. Heroes from various backgrounds have shown their own individuality without being left out. Their jokes are the result of having fun and giving vitality and rhythm to the play.


However, 'Avengers 4' is where fatigue increases for some time. Epic history is often delayed and lengthened. Humor fills the gap between delay and procrastination, but sentimentalism is forced in already. Unlike the previous series, it is also somewhat regrettable that there are many alienated characters. Of course, it was an inevitable sacrifice for the grandeur of the series.'''

In [0]:
review_1=np.array([review_1])
review_1_formed=count.transform(review_1)

In [0]:
review_1_formed=lda.transform(review_1_formed)

In [0]:
words=review_1_formed.argsort

In [0]:
review_1_formed.shape

(1, 10)

In [0]:
review_1_formed.argmax()+1

8